deps_config := \
	/home/eden/dev/explore/zephyr-project/boards/arc/arduino_101_sss/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arc/em_starterkit/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arc/quark_se_c1000_ss_devboard/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/96b_carbon/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/96b_nitrogen/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/arduino_101_ble/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/arduino_due/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/bbc_microbit/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/cc3200_launchxl/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/frdm_k64f/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/hexiwear_k64/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf51_blenano/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf51_pca10028/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52840_pca10056/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52_pca10040/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f103rb/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f401re/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f411re/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_l476rg/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/olimexino_stm32/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/qemu_cortex_m3/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/quark_se_c1000_ble/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/stm3210c_eval/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/stm32_mini_a15/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/v2m_beetle/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/nios2/altera_max10/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/nios2/qemu_nios2/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/riscv32/qemu_riscv32/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/riscv32/zedboard_pulpino/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/arduino_101/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/galileo/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/minnowboard/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/qemu_x86/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/quark_d2000_crb/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/quark_se_c1000_devboard/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_x1000/Kconfig.defconfig.quark_x1000 \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.curie \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.quark_se_c1000 \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_d2000/Kconfig.defconfig.quark_d2000 \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_d2000/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_x1000/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.cc3200 \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l476xx \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f401xe \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f411xe \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103xb \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103xe \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f107xc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.mk64f12 \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52832 \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52840 \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAA \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAB \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAC \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/beetle/Kconfig.defconfig.beetle_r0 \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/beetle/Kconfig.defconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em11d/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em7d/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em9d/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/quark_se_c1000_ss/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/nios2/soc/nios2-qemu/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/nios2/soc/nios2f-zephyr/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/riscv32/soc/pulpino/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/riscv32/soc/riscv32-qemu/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/atom/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/ia32/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/Kconfig.defconfig \
	/home/eden/dev/explore/zephyr-project/tests/ztest/Kconfig \
	/home/eden/dev/explore/zephyr-project/tests/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/debug/segger/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/debug/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/fs/fat/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/fs/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/lib/crypto/mbedtls/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/lib/crypto/tinycrypt/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/lib/crypto/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/ti/cc3200sdk/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/st/stm32cube/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/qmsi/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/nxp/mcux/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/nordic/mdk/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/cmsis/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/hal/Kconfig \
	/home/eden/dev/explore/zephyr-project/ext/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/shell/modules/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/shell/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/debug/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/logging/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/lib/http/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/lib/mqtt/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/lib/dns/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/lib/zoap/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/lib/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.samples \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.stats \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.rpl \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.mgmt \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/l2/ieee802154/Kconfig.radio \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/l2/ieee802154/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/l2/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.stack \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.ipv4 \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.ipv6 \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig.debug \
	/home/eden/dev/explore/zephyr-project/subsys/net/ip/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/net/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/disk/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/bluetooth/controller/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/bluetooth/host/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/bluetooth/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/usb/class/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/usb/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/fs/Kconfig \
	/home/eden/dev/explore/zephyr-project/subsys/Kconfig \
	/home/eden/dev/explore/zephyr-project/lib/libc/Kconfig \
	/home/eden/dev/explore/zephyr-project/lib/Kconfig \
	/home/eden/dev/explore/zephyr-project/misc/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/usb/device/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/usb/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/dma/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/counter/Kconfig.tmr_cmsdk_apb \
	/home/eden/dev/explore/zephyr-project/drivers/counter/Kconfig.qmsi \
	/home/eden/dev/explore/zephyr-project/drivers/counter/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/tmp112/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/tmp007/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/th02/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/sx9500/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/sht3xd/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/nrf5/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/mpu6050/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/mcp9808/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/max44009/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lsm9ds0_mfd/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lsm9ds0_gyro/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lsm6ds0/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lps25hb/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lis3mdl/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/lis3dh/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/isl29035/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/hts221/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/hp206c/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/hmc5883l/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/hdc1008/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/fxos8700/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/dht/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/bmi160/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/bmg160/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/bme280/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/bmc150_magn/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/bma280/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/ak8975/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/sensor/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/flash/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/aio/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/ipm/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.beetle \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.stm32l4x \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.stm32f4x \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.stm32f107xx \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.stm32f10x \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.quark_se \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig.nrf5 \
	/home/eden/dev/explore/zephyr-project/drivers/clock_control/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/watchdog/Kconfig.cmsdk_apb \
	/home/eden/dev/explore/zephyr-project/drivers/watchdog/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/watchdog/Kconfig.qmsi \
	/home/eden/dev/explore/zephyr-project/drivers/watchdog/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/rtc/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/adc/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/pinmux/Kconfig.beetle \
	/home/eden/dev/explore/zephyr-project/drivers/pinmux/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/pinmux/Kconfig.mcux \
	/home/eden/dev/explore/zephyr-project/drivers/pinmux/dev/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/pinmux/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig.k64 \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig.dw \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig.qmsi \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig.pca9685 \
	/home/eden/dev/explore/zephyr-project/drivers/pwm/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/i2c/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/spi/Kconfig.dw \
	/home/eden/dev/explore/zephyr-project/drivers/spi/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/shared_irq/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.pulpino \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.cc32xx \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.cmsdk_ahb \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.nrf5 \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.atmel_sam3 \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.mcux \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.sch \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.qmsi \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.pcal9535a \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig.dw \
	/home/eden/dev/explore/zephyr-project/drivers/gpio/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/pci/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/grove/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/random/Kconfig.mcux \
	/home/eden/dev/explore/zephyr-project/drivers/random/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/timer/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/interrupt_controller/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/interrupt_controller/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.riscv_qemu \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.cmsdk_apb \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.cc32xx \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.altera_jtag \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.nrf5 \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.stm32 \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.qmsi \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.atmel_sam3 \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.nsim \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.stellaris \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.k20 \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig.ns16550 \
	/home/eden/dev/explore/zephyr-project/drivers/serial/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/slip/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/ethernet/Kconfig.dw \
	/home/eden/dev/explore/zephyr-project/drivers/ethernet/Kconfig.mcux \
	/home/eden/dev/explore/zephyr-project/drivers/ethernet/Kconfig.enc28j60 \
	/home/eden/dev/explore/zephyr-project/drivers/ethernet/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/console/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/ieee802154/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/bluetooth/nble/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/bluetooth/hci/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/bluetooth/Kconfig \
	/home/eden/dev/explore/zephyr-project/drivers/Kconfig \
	/home/eden/dev/explore/zephyr-project/kernel/Kconfig.power_mgmt \
	/home/eden/dev/explore/zephyr-project/kernel/Kconfig.event_logger \
	/home/eden/dev/explore/zephyr-project/kernel/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/96b_nitrogen/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/cc3200_launchxl/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52840_pca10056/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52_pca10040/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/x86/galileo/Kconfig \
	/home/eden/dev/explore/zephyr-project/boards/arc/arduino_101_sss/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arc/em_starterkit/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arc/quark_se_c1000_ss_devboard/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/96b_carbon/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/96b_nitrogen/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/arduino_101_ble/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/arduino_due/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/bbc_microbit/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/cc3200_launchxl/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/frdm_k64f/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/hexiwear_k64/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf51_blenano/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf51_pca10028/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52840_pca10056/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nrf52_pca10040/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f103rb/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f401re/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_f411re/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/nucleo_l476rg/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/olimexino_stm32/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/qemu_cortex_m3/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/quark_se_c1000_ble/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/stm3210c_eval/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/stm32_mini_a15/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/arm/v2m_beetle/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/nios2/altera_max10/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/nios2/qemu_nios2/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/riscv32/qemu_riscv32/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/riscv32/zedboard_pulpino/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/arduino_101/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/galileo/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/minnowboard/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/qemu_x86/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/quark_d2000_crb/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/x86/quark_se_c1000_devboard/Kconfig.board \
	/home/eden/dev/explore/zephyr-project/boards/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_d2000/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_x1000/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/core/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_d2000/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_se/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/quark_x1000/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/atom/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/ia32/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/x86/soc/intel_quark/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/riscv32/soc/pulpino/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/riscv32/soc/riscv32-qemu/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/nios2/soc/nios2-qemu/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/nios2/soc/nios2f-zephyr/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f4/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32l4/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/beetle/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/core/cortex_m/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/core/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f1/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32f4/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/stm32l4/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/k6x/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/beetle/Kconfig.series \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/arm/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/atmel_sam3/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nordic_nrf5/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/nxp_kinetis/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/st_stm32/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_lm3s6965/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arm/soc/ti_simplelink/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/quark_se_c1000_ss/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em11d/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em7d/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/em9d/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arc/soc/quark_se_c1000_ss/Kconfig.soc \
	/home/eden/dev/explore/zephyr-project/arch/arc/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/arm/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/nios2/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/riscv32/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/x86/Kconfig \
	/home/eden/dev/explore/zephyr-project/arch/Kconfig \
	/home/eden/dev/explore/zephyr-project/Kconfig.zephyr \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(KERNELVERSION)" "1.6.99"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
